name: labeling_workflow

on:
  issues:
    types: [opened, edited, reopened, labeled]
    
jobs:
  label_issue:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1 
           
      - name: label
        uses: ./.github/actions/issuelabeler
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          number: ${{github.event.issue.number}}
